# Generated by Django 6.0.7 on 2026-07-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'HR Administrator'), ('EMPLOYEE', 'Employee'), ('APPLICANT', 'Applicant')], default='APPLICANT', max_length=20),
        ),
    ]
