# Generated by Django 6.0.7 on 2026-07-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_is_read_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
    ]
