services:
  - type: web
    name: hire-tracker-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://hire-tracker-backend-95mr.onrender.com/api
